name: AuthMeGUI
main: cn.apisium.authme.gui.Main
version: @version@-@apiversion@
website: https://www.apisium.cn
author: Baleine_2000
description: Add a sign gui for AuthMe
depend: [ProtocolLib, AuthMe]